name: Destination Wedding Photographer
favicon: null
layout_spectrum: 0.6469717787113041
typography_spectrum: 0.8462703239638358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.38461912609636784
  lightness: 0.8058852695394307
  saturation: 0.08048591879196465
  rhythmicContrast: 0.18332269485108554
purpose: []
